name: KornKommuniziert
favicon: null
layout_spectrum: 0.97596
typography_spectrum: 0.07312
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c6c6c6'
    - '#706f6f'
    - '#eb5c24'
    - '#000000'
    - '#ff0000'
  brandStrength: 0.25
  lightness: 0.5581227508373559
  saturation: 0.9207812927197665
  rhythmicContrast: 0.7514443399850279
purpose: []
