name: KornKommuniziert
favicon: null
layout_spectrum: 0.01387
typography_spectrum: 0.07312
title: Uli Korn twist Marketing Workshops Moderation Coaching Vorträge
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c6c6c6'
    - '#706f6f'
    - '#eb5c24'
    - '#000000'
    - '#ff0000'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
